### ISSUE TITLE
Can not import template

### ISSUE THREAD

**Issue by akuz84** [larcorba/Larcorba-Zabbix-templates-Juniper-QFX5110-SNMPv3#1]
Hello!

I tried to import template for QFX5110 with Zabbix 4.2.1 but no luck because template has hard version definition 4.4. This issue i resolved by file edit. After that i tried to import modified template, but got "Invalid tag "/zabbix_export/templates/template(1)": the tag "description" is missing.". Also i tried to import template with Zabbix 4.4 running in Docker, but got same issue "Invalid tag "/zabbix_export/templates/template(1)".

**Comment by larcorba** [comment]
Hi Akuz,

I make all my templates directly in our Zabbix 4.4.0 installation and export them for upload. I do not see the template(1) tag description anywhere in the file or any reason why you shouldn't be able to add the template.

Have you tried uploading the .xml in your Zabbix 4.4 Docker installation directly in the WebGUI with the import function? Did you try in in that installation without your edit? I do not seem to be able to replicate this import error on my personal Debian based Zabbix installation.

I just uploaded a new version, perhaps this one works for you?

Kind regards,

Nathan
